In [1]:
from data_provider.data_factory import data_provider
from utils.tools import EarlyStopping, adjust_learning_rate, visual, vali, test
from torch.utils.data import Subset
from tqdm import tqdm
from models.PatchTST import PatchTST
from models.GPT4TS import GPT4TS
from models.DLinear import DLinear
from models.TEMPO import TEMPO
# from models.T5 import T54TS
from models.ETSformer import ETSformer


import numpy as np
import torch

In [2]:
import torch.nn as nn
from torch import optim
from numpy.random import choice

import os
import time

import warnings
import matplotlib.pyplot as plt
import numpy as np

import argparse
import random
import sys

from omegaconf import OmegaConf

import torch.nn as nn
from torch import optim
from numpy.random import choice

import os
import time

import warnings
import matplotlib.pyplot as plt
import numpy as np

import argparse
import random
import sys

from omegaconf import OmegaConf

In [4]:
def get_init_config(config_path=None):
    config = OmegaConf.load(config_path)
    return config

In [17]:
from omegaconf import OmegaConf

# Define the configuration dictionary
config = {
    "datasets": {
        "Solar": {
            "root_path": "/u/dcao1/workspace/Generative-TS-train_all/csdi_data/solar_nips/",
            "data_path": "test/test.csv",
            "data_name": "Solar",
            "data": "solar",
            "lradj": "type4",
            "features": "M",
            "target": "400001",
            "embed": "timeF",
            "freq": 0,
            "percent": 100
        }
    }
}

# Create an OmegaConf object from the dictionary
cfg = OmegaConf.create(config)


In [18]:

# Save the configuration to a YAML file
with open("./configs/custom_dataset.yml", "w") as f:
    OmegaConf.save(cfg, f)

print("Configuration saved to ./configs/custom_dataset.yml")

Configuration saved to ./configs/custom_dataset.yml


In [19]:
config = {
    "description": "TEMPO",
    "checkpoints": "checkpoints/lora_revin_6domain_checkpoints_1/",
    "task_name": "long_term_forecast",
    "prompt": 1,
    "num_nodes": 1,
    "seq_len": 168,
    "pred_len": 30,
    "label_len": 30,
    "decay_fac": 0.5,
    "learning_rate": 0.001,
    "batch_size": 256,
    "num_workers": 0,
    "train_epochs": 10,
    "lradj": "type3",
    "patience": 5,
    "gpt_layers": 6,
    "is_gpt": 1,
    "e_layers": 3,
    "d_model": 768,
    "n_heads": 4,
    "d_ff": 768,
    "dropout": 0.3,
    "enc_in": 7,
    "c_out": 1,
    "patch_size": 16,
    "kernel_size": 25,
    "loss_func": "mse",
    "pretrain": 1,
    "freeze": 1,
    "model": "TEMPO",
    "stride": 8,
    "max_len": -1,
    "hid_dim": 16,
    "tmax": 20,
    "itr": 3,
    "cos": 1,
    "equal": 1,
    "pool": False,
    "no_stl_loss": False,
    "stl_weight": 0.001,
    "config_path": "./configs/custom_dataset.yml",
    "datasets": "ETTm1,ETTh1,ETTm2,electricity,traffic,weather",
    "target_data": "Solar",
    "use_token": 0,
    "electri_multiplier": 1,
    "traffic_multiplier": 1,
    "embed": "timeF",
    "percent": 100,
    "model_id": "prob_TEMPO_6_prompt_learn_168_30_100_sl336_ll30_pl30_dm768_nh4_el3_gl6_df768_ebtimeF_itr0"
}

# Create an OmegaConf object from the dictionary
cfg = OmegaConf.create(config)

# Save the configuration to a YAML file
with open("configs/etth2_config.yml", "w") as f:
    OmegaConf.save(cfg, f)

print("Configuration written to config.yml")

Configuration written to config.yml


In [20]:
config = get_init_config(cfg.config_path)

In [21]:
SEASONALITY_MAP = {
   "minutely": 1440,
   "10_minutes": 144,
   "half_hourly": 48,
   "hourly": 24,
   "daily": 7,
   "weekly": 1,
   "monthly": 12,
   "quarterly": 4,
   "yearly": 1
}

In [22]:
device = torch.device('cuda:0')

In [23]:
if cfg.model == 'PatchTST':
    model = PatchTST(cfg, device)
    model.to(device)
elif cfg.model == 'DLinear':
    model = DLinear(cfg, device)
    model.to(device)
elif cfg.model == 'TEMPO':
    model = TEMPO(cfg, device)
    model.to(device)
elif cfg.model == 'T5':
    model = T54TS(cfg, device)
    model.to(device)
elif 'ETSformer' in cfg.model:
    model = ETSformer(cfg, device)
    model.to(device)
else:
    model = GPT4TS(cfg, device)


params = model.parameters()
model_optim = torch.optim.Adam(params, lr=cfg.learning_rate)

early_stopping = EarlyStopping(patience=cfg.patience, verbose=True)
if cfg.loss_func == 'mse':
    criterion = nn.MSELoss()
elif cfg.loss_func == 'smape':
    class SMAPE(nn.Module):
        def __init__(self):
            super(SMAPE, self).__init__()
        def forward(self, pred, true):
            return torch.mean(200 * torch.abs(pred - true) / (torch.abs(pred) + torch.abs(true) + 1e-8))
    criterion = SMAPE()

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(model_optim, T_max=cfg.tmax, eta_min=1e-8)

trainable params: 308736 || all params: 82207488 || trainable%: 0.38


In [24]:
model_path = os.path.join(cfg.checkpoints, cfg.model_id)
best_model_path = model_path + '/checkpoint.pth'
print(best_model_path)
model.load_state_dict(torch.load(best_model_path,  map_location=torch.device(device)), strict=False)
print("------------------------------------")

checkpoints/lora_revin_6domain_checkpoints_1/prob_TEMPO_6_prompt_learn_168_30_100_sl336_ll30_pl30_dm768_nh4_el3_gl6_df768_ebtimeF_itr0/checkpoint.pth
------------------------------------


In [25]:
cfg.data = config['datasets'][cfg.target_data].data
cfg.root_path = config['datasets'][cfg.target_data].root_path
cfg.data_path = config['datasets'][cfg.target_data].data_path
cfg.data_name = config['datasets'][cfg.target_data].data_name
cfg.features = config['datasets'][cfg.target_data].features
cfg.freq = config['datasets'][cfg.target_data].freq
cfg.target = config['datasets'][cfg.target_data].target
cfg.embed = config['datasets'][cfg.target_data].embed
cfg.percent = config['datasets'][cfg.target_data].percent
cfg.lradj = config['datasets'][cfg.target_data].lradj
if cfg.freq == 0:
    cfg.freq = 'h'
cfg.seq_len = 168 + 24
cfg.pred_len = 24 
test_data, test_loader = data_provider(cfg, 'test')

self.enc_in = 137
self.data_x = (7, 137)
test 7


In [38]:
test_data.mean_data

array([ 87.58765 ,  38.1089  ,  36.878876,  38.680717,  74.740814,
       100.72187 ,  34.929775,  34.72166 ,  38.54339 ,  36.66024 ,
        36.24879 ,  20.498371,  38.83451 ,  36.9731  ,  39.425587,
        24.803717,  38.698612,  38.37145 ,  36.375454,  36.688168,
        38.70079 ,  38.435272,  48.711697,  81.96147 ,  38.615086,
        32.350006,  36.39808 ,  38.585712,  81.54733 ,  36.545185,
        36.812992,  71.320625,  38.59133 ,  34.578987,  34.22856 ,
        30.669676,  38.383503,  27.520584,  38.10523 ,  36.47746 ,
        90.69661 ,  37.280773,  39.652153,  36.49171 ,  62.690407,
        37.48001 ,  27.493147,  34.83882 ,  38.150475,  37.91924 ,
        38.649918,  36.806263,  38.122124,  38.63643 ,  34.987503,
        38.54304 ,  38.58559 ,  34.352345,  34.68059 ,  38.409283,
        27.211773,  39.226173,  36.36521 ,  34.60476 ,  36.09768 ,
        37.850525,  39.01769 ,  38.383133,  81.14679 ,  71.17894 ,
        51.486794,  26.875301,  36.03495 , 124.58435 ,  38.810

In [27]:
# %%
import torch.distributions as dist
preds = []
trues = []
# mases = []

# Initialize accumulators for errors
total_mae = 0
total_mse = 0
n_samples = 0
itr = 0

cfg.seq_len = 168
cfg.pred_len = 24
model.eval()
# import pdb; pdb.set_trace()
with torch.no_grad():
    for i in range(len(test_data)):
        #enumerate(test_loader): #tqdm(enumerate(test_loader), total=len(test_loader)):
        data = test_data[i]
        seq_x, text_embedding, observed_mask = data[0].to(device), data[1].to(device), data[2].to(device)
        seq_x = seq_x.float().to(device)
        batch_x = seq_x[:, :cfg.seq_len].unsqueeze(-1) # 137, 168, 1
        batch_y = seq_x[:,cfg.seq_len:cfg.seq_len+cfg.pred_len]
        trues.append(batch_y.cpu().numpy())

                        
        outputs, _ = model(batch_x, 0, None, None, None) #+ model(seq_seasonal, ii) + model(seq_resid, ii)

        mu, sigma, nu = outputs[0], outputs[1], outputs[2]
        # Create the Student's t-distribution with the predicted parameters
        student_t = dist.StudentT(df=nu, loc=mu, scale=sigma)

        # Generate 30 samples for each prediction
        num_samples = 35
        probabilistic_forecasts = student_t.rsample((num_samples,))

        # The shape of probabilistic_forecasts will be (num_samples, batch_size, pred_length)
        print(probabilistic_forecasts.shape)
        preds.append(probabilistic_forecasts.cpu().numpy())


torch.Size([35, 137, 30])
torch.Size([35, 137, 30])
torch.Size([35, 137, 30])
torch.Size([35, 137, 30])
torch.Size([35, 137, 30])
torch.Size([35, 137, 30])
torch.Size([35, 137, 30])


In [33]:
trues[0]

array([[-0.81706506, -0.81706506, -0.81706506, ..., -0.81706506,
        -0.81706506, -0.81706506],
       [-0.72572196, -0.72572196, -0.72572196, ..., -0.72572196,
        -0.72572196, -0.72572196],
       [-0.71024656, -0.71024656, -0.71024656, ..., -0.71024656,
        -0.71024656, -0.71024656],
       ...,
       [-0.7138923 , -0.7138923 , -0.7138923 , ..., -0.7138923 ,
        -0.7138923 , -0.7138923 ],
       [-0.8102401 , -0.8102401 , -0.8102401 , ..., -0.8102401 ,
        -0.8102401 , -0.8102401 ],
       [-0.71037203, -0.71037203, -0.71037203, ..., -0.71037203,
        -0.71037203, -0.71037203]], dtype=float32)

In [35]:
preds[0]

array([[[-0.9282118 , -0.6960738 , -0.7322746 , ..., -0.77908736,
         -0.6711371 , -0.43116292],
        [-0.7405034 , -0.71399134, -0.7741934 , ..., -0.65870476,
         -0.62544435, -0.6820428 ],
        [-0.5781708 , -0.6374622 , -0.6082664 , ..., -0.8387711 ,
         -0.840068  , -0.8321725 ],
        ...,
        [-0.58394253, -0.5504097 , -0.67426914, ..., -0.775542  ,
         -0.97133744, -0.2898679 ],
        [-0.834128  , -0.8469678 , -0.8209683 , ..., -0.7103567 ,
         -0.9341038 , -0.16032001],
        [-0.6759638 , -0.79649895, -0.84350353, ..., -0.8641352 ,
         -0.72463834, -0.34910887]],

       [[-0.8016211 , -0.79438305, -0.70365155, ..., -0.75734043,
         -0.6961845 , -0.4723705 ],
        [-0.7371537 , -0.6779119 , -0.7249288 , ..., -0.5984942 ,
         -0.742493  , -0.36965835],
        [-0.7520069 , -0.6641639 , -0.6075448 , ..., -0.3887201 ,
         -0.27037713, -0.4239577 ],
        ...,
        [-0.797414  , -0.7909659 , -0.66514206, ..., -

In [32]:
np.array(preds).shape, np.array(trues).shape

((7, 35, 137, 30), (7, 137, 24))

In [82]:
gt_data = np.array(trues)
synthetic_data = np.array(preds)

In [83]:
synthetic_data = synthetic_data[:,:,:, :gt_data.shape[2]]
target_mask = np.ones_like(gt_data)

In [74]:
# synthetic_data = np.swapaxes(synthetic_data, -1, -2)
# gt_data = np.swapaxes(gt_data, -1, -2)
# synthetic_data.shape

In [42]:
from metrics.imputation_metrics import mse_withmask, mae_withmask, calc_quantile_CRPS, calc_quantile_CRPS_sum

In [75]:
calc_quantile_CRPS_sum(torch.Tensor(gt_data),torch.Tensor(synthetic_data),torch.Tensor(target_mask),mean_scaler=0,scaler=1)

0.98885767083419

In [76]:
# synthetic_data = np.array(synthetic_data).reshape(synthetic_data.shape[0],-1,synthetic_data.shape[2],synthetic_data.shape[3])
# gt_data = np.array(gt_data).reshape(gt_data.shape[0],gt_data.shape[2], -1)
# target_mask = np.ones_like(gt_data)

In [84]:
unormzalized_gt_data = []
for g in gt_data:
    unormzalized_gt_data.append(np.transpose(np.transpose(g)*test_data.std_data+test_data.mean_data))
unormzalized_gt_data = np.array(unormzalized_gt_data)
unormalized_synthetic_data = []
for i in range(len(synthetic_data)):
    for j in range(len(synthetic_data[i])):
        s = synthetic_data[i][j]
        unormalized_synthetic_data.append(np.transpose(np.transpose(s)*test_data.std_data+test_data.mean_data))
unormalized_synthetic_data = np.array(unormalized_synthetic_data).reshape(synthetic_data.shape[0],-1,synthetic_data.shape[2],synthetic_data.shape[3])
unormzalized_gt_data.shape,unormalized_synthetic_data.shape

((7, 137, 24), (7, 35, 137, 24))

In [88]:
unormzalized_gt_data.shape

(7, 24, 137)

In [89]:
unormalized_synthetic_data.shape

(7, 35, 24, 137)

In [90]:
gt_data.shape

(7, 24, 137)

In [85]:
unormalized_synthetic_data = np.swapaxes(unormalized_synthetic_data, -1, -2)
unormzalized_gt_data = np.swapaxes(unormzalized_gt_data, -1, -2)


In [91]:
target_mask = np.ones_like(unormzalized_gt_data)

In [92]:
calc_quantile_CRPS_sum(torch.Tensor(unormzalized_gt_data),torch.Tensor(unormalized_synthetic_data),torch.Tensor(target_mask),mean_scaler=0,scaler=1)


0.46642715052554484